# Configuration file containing regression models and their repective parameters

models:
  # - name: "Linear"
  #   parameters:
  #     fit_intercept: True
  #     n_jobs: -1
 
  # - name: "Forest"
  #   parameters:
  #     n_estimators: 800
  #     criterion: "squared_error"
  #     max_features: "log2"
  #     max_samples: 8
  #     max_depth: 5
  #     n_jobs: -1
  #     random_state: 42

  - name: "CatBoost"
    parameters:
      iterations: 1000
      learning_rate: 0.05
      max_depth: 5
      loss_function: "RMSE"
      subsample: 0.5
      verbose: 0
      random_state: 42 
  - name: "XGBoost"
    parameters:
      n_estimators: 800
      learning_rate: 0.1
      objective: "reg:squarederror"
      subsample: .5
      colsample_bytree: .47
      n_jobs: -1
      random_state: 42
  - name: "LightGBM"
    parameters: 
      n_estimators: 300
      boosting_type: "gbdt"
      learning_rate: 0.05
      num_leaves: 20
      max_depth: 5
      subsample: .63
      colsample_bytree: .63
      verbose: 0
      n_jobs: -1
      random_state: 42

